# -*- coding: utf-8 -*-
TOWNS = [
dict(slug='air-conditioning-wigan', town='Wigan', county='Greater Manchester',
 postcodes='WN1 to WN6, including Standish, Orrell and Ashton in Makerfield', drive='35 minutes',
 lat=53.5450, lon=-2.6318,
 title='Air Conditioning Wigan | Install &amp; Service | CoolIn',
 desc='Air conditioning in Wigan, Standish and Orrell. Terraced housing, retail parks and light industrial units. Free survey, 0% VAT on domestic installations.',
 intro='Dense terraced housing across the older parts of town, newer estates out towards Standish and Orrell, and a wide industrial and retail belt that generates most of the commercial work.',
 stock='Wigan terraces are typically narrow, deep and built right up to the pavement, which makes the outdoor unit position the first thing we work out rather than the last.',
 local=[('Narrow terraces','Rear yards are often only two or three metres deep. The 2025 permitted development change that removed the one metre boundary rule opened up a lot of these, because the condenser can now sit on brackets against the yard wall.'),
        ('Rear alleys and shared access','Where the yard genuinely will not take a unit, a wall bracket at first floor level or a position on a rear outrigger usually will. Worth surveying before assuming it cannot be done.'),
        ('Retail parks and trade counters','Robin Park and the units around it: large glazed frontages, doors open through trading hours, and dust in the workshop spaces behind.'),
        ('Light industrial','Older units with poor insulation and flat roofs that radiate heat all afternoon. Spot cooling over the occupied areas is nearly always the economic answer.')],
 faqs=[('My yard is tiny. Can the outdoor unit still go outside?',
        'Almost certainly. A domestic condenser needs roughly 300mm of clear space behind it and about a metre in front for airflow, and it can be wall mounted on brackets rather than standing on the floor. Since 29 May 2025 there is no longer a minimum distance from the boundary for permitted development, which made a great many small terraced yards viable that previously were not.'),
       ('Can you fit it if there is no rear access?',
        'Usually yes. Pipework can run internally through a cupboard or riser and out at a higher level, or the condenser can go on a bracket above the yard. It adds to the pipe run and therefore the price, which is exactly the sort of thing we would rather establish at the free survey than halfway up a wall.')]),

dict(slug='air-conditioning-southport', town='Southport', county='Merseyside',
 postcodes='PR8 and PR9, including Birkdale, Ainsdale and Formby', drive='60 minutes',
 lat=53.6458, lon=-3.0104,
 title='Air Conditioning Southport | Install &amp; Service | CoolIn',
 desc='Air conditioning in Southport, Birkdale and Formby. Coastal grade units against salt corrosion, Victorian villas and Lord Street retail. Free survey, 0% VAT.',
 intro='A Victorian seaside town where the sea air is the deciding technical factor. Salt attacks a standard outdoor coil in a way it never does inland, and specifying for that is the difference between a condenser lasting fifteen years and seven.',
 stock='Southport, Birkdale and Formby sit close enough to open water that corrosion protection should be part of every specification, not an upgrade.',
 local=[('Salt air corrosion','Airborne salt eats the aluminium fins on a standard outdoor coil. Within roughly a mile of open water we specify coated coil versions of the same units as standard. It is a modest premium and it adds years to the life of the condenser.'),
        ('Victorian and Edwardian villas','Large, high ceilinged, often converted into flats. Where a building is in multiple occupation, a shared plant position agreed with the freeholder usually beats six separate condensers on one elevation.'),
        ('Lord Street and the conservation area','The canopied frontages and the conservation designation limit what can go on a street elevation. Rear and courtyard positions, agreed in advance.'),
        ('Hotels and guest houses','Room by room control matters more than raw capacity, and fitting has to work around occupancy. We programme these floor by floor, out of season where possible.')],
 faqs=[('Does living near the coast really affect the unit?',
        'Yes, and it is the single most important specification decision in Southport. Salt in the air corrodes the aluminium fins of a standard outdoor coil, and a condenser that would run fifteen years in Manchester can start failing in seven within a mile of the sea. Every major manufacturer makes a coated coil version of the same unit for a modest premium. We fit those as standard on coastal addresses and we would rather explain why than quote cheaper and see it back in year eight.'),
       ('Are you not a long way from Southport for a breakdown?',
        'It is about an hour from us, which is the outer edge of our normal area. We are honest about what that means: service plan customers still get next working day attendance, but without a plan, in the middle of a July heatwave, you will wait longer than someone in Salford. If that matters to you, the service plan is doing real work rather than being an upsell.')]),

dict(slug='air-conditioning-blackburn', town='Blackburn', county='Lancashire',
 postcodes='BB1 and BB2, including Darwen, Great Harwood and Mellor', drive='50 minutes',
 lat=53.7486, lon=-2.4820,
 title='Air Conditioning Blackburn | Install &amp; Service | CoolIn',
 desc='Air conditioning in Blackburn and Darwen. Mill town terraces, industrial units and town centre commercial. Free survey, 0% VAT on domestic installations.',
 intro='A Lancashire mill town with the housing and industrial stock that goes with it. Long rows of solid wall terraces, substantial former mill buildings now in mixed use, and a manufacturing base that needs process cooling as much as comfort.',
 stock='Blackburn work skews commercial and industrial, and the domestic side is almost entirely pre cavity wall construction.',
 local=[('Solid wall terraces','No cavity, so heat crosses the wall in both directions faster than in a modern house. Both the heating and cooling loads run higher than floor area suggests, and we size on the construction rather than the square metres.'),
        ('Mill buildings in mixed use','Enormous volumes, single glazing in places and exposed brick with no insulation. Conditioning the whole floor plate is rarely economic. Zoned cooling over the occupied areas is.'),
        ('Manufacturing and process','Where cooling protects equipment or a process rather than people, the tolerance is tighter and a failure costs more. That usually means two systems rather than one, and remote alarms.'),
        ('Darwen and the higher ground','Climbing towards the moors, colder and more exposed, with the same honest conversation about heat pump output on the coldest weeks that we have in Saddleworth.')],
 faqs=[('Is air conditioning worth it in a Lancashire mill town?',
        'The cooling matters for perhaps eight weeks a year. The heating matters for six months, and that is where these systems earn their keep here. Warming one or two rooms you actually use, at roughly a quarter of the cost of the same heat from an electric heater, makes more financial sense in Blackburn than the summer cooling does. The cooling is the part you will be grateful for in July.'),
       ('Can you cool machinery rather than people?',
        'Yes, and it is a different specification. Process and equipment cooling runs at a constant load year round, tolerates far less variation, and fails expensively. That normally means close control units rather than comfort cooling, a second system so one failure does not stop production, and remote alerting so you know before the machine does.')]),

dict(slug='air-conditioning-crewe', town='Crewe', county='Cheshire East',
 postcodes='CW1 and CW2, including Nantwich, Sandbach and Alsager', drive='50 minutes',
 lat=53.0990, lon=-2.4400,
 title='Air Conditioning Crewe | Install &amp; Service | CoolIn',
 desc='Air conditioning in Crewe, Nantwich and Sandbach. Railway terraces, distribution units and Cheshire village property. Free survey, 0% VAT on domestic work.',
 intro='A railway town surrounded by Cheshire countryside, which makes for two very different jobs a few miles apart: dense railway era terraces in Crewe itself, and period village property at Nantwich and Sandbach.',
 stock='Crewe is also a distribution hub, so a good share of the commercial work is warehouse offices and transport depots rather than high street retail.',
 local=[('Railway era terraces','Built fast and in volume in the nineteenth century, solid wall, small rooms and shallow yards. Straightforward jobs once the outdoor unit position is settled, which is usually the only real question.'),
        ('Nantwich and Sandbach','Timber framed and Georgian property, conservation areas and a scattering of listed buildings. Planning is the first conversation, not the last.'),
        ('Distribution and transport depots','Offices and control rooms inside large sheds, where the office is often an afterthought thermally and runs ten degrees above the rest of the building.'),
        ('Village pubs and restaurants','Low ceilings, thick walls and kitchens in spaces never designed for them. Extract and make up air have to be designed as a pair.')],
 faqs=[('Do you travel out to Nantwich and Sandbach?',
        'Yes, they are inside our normal working area, roughly fifty minutes from base. The survey is free and there is no travel charge anywhere inside the area we cover. What we will not do is take on an address so far out that we cannot service it properly afterwards, because a system nobody comes back to is worth less than no system.'),
       ('Is a timber framed building a problem?',
        'Not a problem, but it needs care and it is not a job to rush. Drilling through a historic timber frame is avoided wherever there is an alternative route, fixings go into the right places, and in most cases these buildings are listed or in a conservation area, which limits where the outdoor unit can sit. All of that is settled at survey before any equipment is ordered.')]),

dict(slug='air-conditioning-northwich', town='Northwich', county='Cheshire West and Chester',
 postcodes='CW8 and CW9, including Winsford, Middlewich and Knutsford', drive='40 minutes',
 lat=53.2593, lon=-2.5170,
 title='Air Conditioning Northwich | Install &amp; Service | CoolIn',
 desc='Air conditioning in Northwich, Knutsford and Winsford. Cheshire village property, riverside homes and chemical industry units. Free survey, 0% VAT.',
 intro='Cheshire salt country, with a long industrial history alongside some of the most attractive village property in the county. Knutsford in particular brings the conservation constraints, while the Northwich industrial belt brings process and plant work.',
 stock='The split here is unusually wide: period village housing on one side and heavy industry on the other, often within ten minutes of each other.',
 local=[('Knutsford and the villages','Conservation areas, listed frontages and streets where nothing is permitted on a public elevation. Rear and courtyard positions, agreed before quoting.'),
        ('Riverside and flood zone property','Where a property sits in a flood risk area, ground mounted condensers are raised on stands above the likely water level. It costs very little at installation and saves the unit.'),
        ('Industrial and process plant','The chemical and manufacturing sites around Northwich need cooling that protects equipment. Different tolerances, different specification, usually duplicated systems.'),
        ('Modern estates at Winsford','Newer, better insulated housing with the overheating profile that goes with it. Sized on glazing and orientation rather than floor area.')],
 faqs=[('My property floods. Where does the outdoor unit go?',
        'Off the ground. A condenser can be mounted on a raised stand or on wall brackets well above the likely water level, which costs very little at installation and saves a unit that would otherwise be written off. It also keeps the electrical connection out of harm. We check flood risk at survey for any riverside address rather than assuming.'),
       ('Is Knutsford a conservation area?',
        'Large parts of the centre are, and there are listed buildings scattered through it. In a conservation area permitted development still applies but the outdoor unit must not sit nearer to a bounding highway than the building itself, which in practice means rear or courtyard positions. Listed buildings have no permitted development rights and need consent, which we prepare.')]),

dict(slug='air-conditioning-leigh', town='Leigh', county='Greater Manchester',
 postcodes='WN7, and into Atherton, Tyldesley and Astley', drive='30 minutes',
 lat=53.4974, lon=-2.5152,
 title='Air Conditioning Leigh | Install &amp; Service | CoolIn',
 desc='Air conditioning in Leigh, Atherton and Tyldesley. Former mill and mining terraces, modern estates and local business units. Free survey, 0% VAT.',
 intro='A former cotton and mining town between Manchester and Wigan, with long rows of solid wall terraces, pockets of newer estate housing, and a steady base of small business and trade units.',
 stock='Leigh is a straightforward patch technically. Most domestic work is terraces and semis, and most commercial work is small units, shops and takeaways.',
 local=[('Terraces and semis','Solid wall on the older stock, cavity on the interwar semis, and the difference changes the sizing noticeably. We check the construction rather than guessing from the street.'),
        ('Modern estate housing','Better insulated, more glazing, and overheating in the south facing rooms by late spring. Less capacity needed than the floor area suggests, more attention to where the sun lands.'),
        ('Shops and takeaways','Small kitchens, heavy extract requirements and almost no space for plant. Getting the make up air right is what stops the extract starving and the heat backing into the counter area.'),
        ('Small business units','Trade counters and workshops where dust is the enemy of the filter, and the service interval has to reflect that rather than following a domestic schedule.')],
 faqs=[('How do I know if my house is solid wall or cavity?',
        'A rough guide is the age: built before about 1920 and it is probably solid wall, after about 1930 and it is probably cavity. The brick pattern helps too, because a solid wall usually shows some bricks laid end on. It matters because a solid wall loses and gains heat faster, so the same room needs more capacity than its floor area suggests. We check it properly at survey, since guessing wrong is how systems end up undersized.'),
       ('Can you fit air conditioning in a takeaway?',
        'Yes, and the cooling is usually the easy half. The harder part is the extract over the cooking line and the make up air that replaces what the canopy pulls out. Without that supply the kitchen runs as a vacuum, the extract rate collapses and the heat pushes forward into the counter area. We design the two together rather than treating the cooling as a separate job.')]),

dict(slug='air-conditioning-ashton-under-lyne', town='Ashton under Lyne', county='Tameside, Greater Manchester',
 postcodes='OL6 and OL7, including Droylsden, Stalybridge and Hyde', drive='25 minutes',
 lat=53.4896, lon=-2.0974,
 title='Air Conditioning Ashton under Lyne | Install | CoolIn',
 desc='Air conditioning in Ashton under Lyne, Stalybridge and Hyde. Tameside terraces, retail parks and canalside conversions. Free survey, 0% VAT on domestic work.',
 intro='A Tameside market town close enough to Manchester for an easy callout, with a mix of Victorian terraces, canalside mill conversions at Stalybridge, and a large retail and leisure footprint around the town centre.',
 stock='Ashton and the Tameside towns around it are among the quicker addresses for us to reach, which shows up in callout response rather than in the price.',
 local=[('Victorian terraces','Solid wall, narrow frontage, small rear yard. The standard Tameside job, and a straightforward one once the outdoor unit position is agreed.'),
        ('Canalside mill conversions','Stalybridge and the canal corridor have a good number of converted mills: high ceilings, single aspect glazing and no ceiling void, so surface trunking that follows the existing services usually beats chasing anything in.'),
        ('Retail and leisure','The retail park and town centre units, trading with doors open and large glazed frontages. Air curtains and correct positioning do more than simply upsizing the system.'),
        ('Rising ground towards Mossley','As you climb out of the valley the exposure increases and the winters lengthen, which is worth factoring into the heating expectation.')],
 faqs=[('How quickly can you get to Ashton for a breakdown?',
        'Around 25 minutes, which puts it among the quickest addresses on our patch. Service plan customers get same day phone support and next working day attendance. Without a plan you go behind contract customers, which through July and August can still mean several days even from this close.'),
       ('Can pipework be hidden in a mill conversion?',
        'Sometimes, but often it should not be. Converted mills rarely have a ceiling void or stud walls to chase into, and cutting into structural brick or exposed beams is both difficult and, in a listed conversion, not permitted. The tidier answer is usually white trunking routed alongside the existing services and conduit, which in a building of that character reads as part of the fabric rather than as an addition.')]),

dict(slug='air-conditioning-lancaster', town='Lancaster', county='Lancashire',
 postcodes='LA1, and into Morecambe, Heysham and Carnforth', drive='75 minutes',
 lat=54.0466, lon=-2.8007,
 title='Air Conditioning Lancaster | Install &amp; Service | CoolIn',
 desc='Air conditioning in Lancaster and Morecambe. Georgian city centre, listed property, student housing and coastal exposure. Free survey, 0% VAT on domestic work.',
 intro='The furthest point we work to, and we say so plainly. A historic city with a dense Georgian and Victorian centre, a large student rental market, and coastal exposure out towards Morecambe and Heysham that brings the same salt problem as Southport.',
 stock='Lancaster is at the very edge of our area at around 75 minutes. We take installation work here and we are straight about what that means for a breakdown in August.',
 local=[('Georgian and listed city centre','A high concentration of listed buildings and conservation area frontages for a city of its size. Consent before anything is fixed to the structure, and rear or courtyard positions as a matter of course.'),
        ('Student and rental property','Landlords want systems that survive a change of tenant every year, cost little to run and have accessible filters. Simple wall units and a service plan that carries across occupiers.'),
        ('Coastal exposure at Morecambe','Same salt corrosion issue as Southport. Within about a mile of open water we specify coated coil units as standard rather than as an upgrade.'),
        ('Distance, stated honestly','At 75 minutes this is beyond our usual hour. Installation is straightforward to programme. Emergency callouts are not, and a service plan is the only thing that makes the response time reliable.')],
 faqs=[('Are you too far away to look after a system in Lancaster?',
        'For installation, no. It is a planned visit and 75 minutes each way is easily programmed. For an emergency callout in the middle of a heatwave, it is honestly the weakest part of our offer, and we would rather say that now than after you have paid. Service plan customers get next working day attendance, which we hold to. Without a plan, at that distance, you may wait. If reliable same week response matters more than anything, a Lancaster based installer may serve you better and we will say so.'),
       ('Does Morecambe need the coastal specification too?',
        'Yes. Anywhere within roughly a mile of open water, salt in the air corrodes the aluminium fins on a standard outdoor coil and can take years off the condenser. Coated coil versions of the same units cost a modest premium and are what we fit as standard on those addresses.')]),
]
