# -*- coding: utf-8 -*-
"""Per town content. Every field is written for that town specifically.
If you add a town, write it properly: a near duplicate page is worse than none."""

TOWNS = [
dict(slug='air-conditioning-altrincham', town='Altrincham', county='Trafford, Greater Manchester',
 postcodes='WA14 and WA15, taking in Hale, Bowdon, Timperley and Dunham', drive='15 minutes',
 lat=53.3873, lon=-2.3488,
 title='Air Conditioning Altrincham | Install &amp; Service | CoolIn',
 desc='Air conditioning installation and servicing in Altrincham, Hale and Bowdon. Period villas, extensions and conservation areas handled. Free survey, 0% VAT.',
 intro='Our closest town, and the one we know best. Large Edwardian villas in Bowdon and Hale, glass extensions that turn into greenhouses by May, and a town centre of independent bars and restaurants that cannot shut for a fit out.',
 stock='Altrincham splits neatly into three jobs: big period houses, modern rear extensions bolted onto them, and a food and drink scene squeezed into small units.',
 local=[('Bowdon and Hale villas','Substantial detached houses with high ceilings, meaning you are cooling volume rather than floor area. Multi split systems running four or five rooms from one condenser keep a single unit on the elevation rather than a row of them.'),
        ('Glass extensions and orangeries','The most common call we get here. A south facing rear extension with bifolds and a lantern roof gains heat faster than almost any other room in a house, and needs sizing on glazing area rather than floor size.'),
        ('Bowdon conservation area','Restricts where the outdoor unit can sit: it must not be nearer a bounding highway than the house itself. That usually means a rear or side position, agreed at survey before anything is quoted.'),
        ('Town centre hospitality','Altrincham Market and the bars around it run small kitchens in tight spaces. Extract with matched make up air, fitted overnight, so the doors open as normal the next day.')],
 faqs=[('Do I need permission for air conditioning in the Bowdon conservation area?',
        'Permitted development still applies, with an extra restriction: the outdoor unit must not sit nearer to a highway bounding the property than any part of the house. In practice that pushes it to a rear or side elevation, which is usually where you would want it anyway. Listed buildings, of which Bowdon has several, have no permitted development rights at all and need consent. We check the designation at survey and tell you before you commit.'),
       ('What size unit does a glass extension need?',
        'More than the floor area suggests. A 20m2 extension with bifolds and a roof lantern can need 5kW where the same 20m2 of ordinary bedroom would take 3.5kW. We size on the glazed area and its orientation, because on a south or west facing extension the glass is doing most of the heating, not the room.')]),

dict(slug='air-conditioning-wilmslow', town='Wilmslow', county='Cheshire East',
 postcodes='SK9, including Alderley Edge, Handforth and Styal', drive='25 minutes',
 lat=53.3243, lon=-2.2264,
 title='Air Conditioning Wilmslow | Install &amp; Service | CoolIn',
 desc='Air conditioning in Wilmslow and Alderley Edge. Large detached homes and discreet installations where nothing shows from the road. Free survey, 0% VAT.',
 intro='Large detached homes where the brief is usually as much about what you cannot see as what you can. Condensers hidden behind planting, pipework inside voids, and indoor units chosen to disappear into a room rather than announce themselves.',
 stock='Wilmslow work tends to be whole house rather than single room, and the finish matters as much as the performance.',
 local=[('Whole house multi splits','Four or five bedrooms plus a study, all running from one or two outdoor units. Getting the condenser count down is usually the design priority, which means sizing carefully so the outdoor unit is not the limiting factor on a hot night.'),
        ('Discreet installation','Slim ducted units above a landing ceiling, with only a linear grille visible, are common here. They cost more than a wall unit and they are the difference between a system you notice and one you do not.'),
        ('Home offices and annexes','Converted garages, garden rooms and above garage offices are rarely on the main heating system and run cold in winter and hot in summer. A single unit fixes both ends of that, cheaply.'),
        ('Pools, gyms and cinema rooms','High heat loads in sealed rooms. These need ventilation designed alongside the cooling, because recirculating the same air harder does nothing for humidity or air quality.')],
 faqs=[('Can you install air conditioning without it being visible from the road?',
        'Almost always. The indoor side can be slim ducted so only a grille shows, and the outdoor unit can go on a side or rear elevation, in a screened enclosure or behind planting, as long as it keeps clear airflow of roughly 300mm behind and a metre in front. Boxing a condenser in tightly to hide it is the one thing that genuinely hurts performance, so we design the screen rather than bolting one on afterwards.'),
       ('Will one outdoor unit run five rooms?',
        'It can, but the outdoor unit caps the total. Five 2.5kW indoor units on a 10kW condenser gives you 10kW shared between them when everything runs at once, not 12.5kW. In a house where all five rooms are occupied on the same hot evening that matters, so we size the condenser against how you actually use the house rather than the theoretical maximum.')]),

dict(slug='air-conditioning-warrington', town='Warrington', county='Cheshire',
 postcodes='WA1 to WA5, including Birchwood, Stockton Heath and Lymm', drive='30 minutes',
 lat=53.3900, lon=-2.5970,
 title='Air Conditioning Warrington | Install &amp; Service | CoolIn',
 desc='Air conditioning in Warrington, Birchwood and Stockton Heath. New build estates, business parks and distribution units. Free survey, 0% VAT on domestic work.',
 intro='Two very different markets in one town. Modern estates at Chapelford and Omega that overheat despite excellent insulation, and a commercial belt of business parks and distribution sheds along the M62 and M6 corridor.',
 stock='Warrington has more new build housing than anywhere else we cover, and more warehouse floor space. Both need a different approach to an old terrace.',
 local=[('New build estates','Airtight and well insulated, which is superb in January and the reason they overheat in June. Solar gain through large windows has nowhere to escape. These homes often need less capacity than their floor area suggests but far more thought about which rooms are getting the sun.'),
        ('Business parks','Birchwood and the office parks off the M62 run floor plates with a cold north side and a glazed south side. Zoned cassettes or VRF with proper controls stop the thermostat war that follows.'),
        ('Distribution and logistics','High bay units where cooling the whole volume is never economic. Spot cooling over pick stations and offices, with destratification fans bringing the warm air back down in winter.'),
        ('Stockton Heath and Lymm','Older village centres with period property and conservation constraints, sitting right next to the new build estates. Same town, completely different survey.')],
 faqs=[('Why does my new build overheat when it is so well insulated?',
        'Because insulation works in both directions. A modern home is built airtight to keep heat in, so when sunlight comes through large south or west facing windows the heat that arrives has nowhere to go. There is no draught to carry it away and the fabric is too light to absorb much. It is common for a new build to run hotter in July than a draughty Victorian house of the same size.'),
       ('Can you cool a warehouse or distribution unit?',
        'Not the whole volume, economically. Cooling a high bay shed to a comfortable temperature costs more than most operations can justify. What works is spot cooling over the areas where people actually stand, packing benches, pick stations and offices, and destratification fans to push warm air back down in winter rather than letting it sit in the roof space.')]),

dict(slug='air-conditioning-salford', town='Salford', county='Greater Manchester',
 postcodes='M3, M5, M6, M7 and M50, including Salford Quays and MediaCity', drive='15 minutes',
 lat=53.4875, lon=-2.2901,
 title='Air Conditioning Salford | Install &amp; Service | CoolIn',
 desc='Air conditioning in Salford and Salford Quays. Apartment blocks, MediaCity offices and converted terraces. Freeholder consent handled. Free survey, 0% VAT.',
 intro='Glass apartment towers at the Quays that bake from March, media and office space around MediaCity, and rows of Victorian terraces a mile inland. Salford covers more building types in a small radius than anywhere else we work.',
 stock='Most Salford enquiries are apartments, and most apartments come with a freeholder, a managing agent and a lease that has something to say about the outside of the building.',
 local=[('Quays apartments','Floor to ceiling glazing facing water, with no shading and windows that open a few inches at most. These flats have no way of shedding heat, which is why they are among the most uncomfortable homes in the region by July.'),
        ('Freeholder and management consent','Nearly every apartment job needs approval before anything is fixed outside. We prepare the request with unit positions, noise figures and photographs, which is the difference between an approval and a refusal.'),
        ('Systems with no outdoor unit','Where a condenser genuinely cannot be fixed to the building, self contained units that vent through a small core hole are the fallback. They are less efficient and noisier than a split, and we will say so, but they work where nothing else is permitted.'),
        ('MediaCity offices and studios','Edit suites and equipment rooms with steady year round heat loads, and open plan floors that need zoning. Out of hours fitting so broadcast and production are never interrupted.')],
 faqs=[('Can I get air conditioning in a Salford Quays apartment?',
        'Usually, but the lease decides. Almost all of them require the freeholder or managing agent to consent to anything fixed to the exterior, and the permitted development limits for flats are tighter than for houses. Where a wall mounted condenser is refused, the options are a balcony position if the lease allows it, a shared plant location agreed with the building manager, or a self contained unit with no outdoor part. We work out which applies at survey rather than after you have paid.'),
       ('Why are apartments so much hotter than houses?',
        'Three reasons stacked on top of each other. Large areas of glazing with no shading, windows restricted to a few inches for safety so there is almost no ventilation, and heat arriving from the flats around and below you rather than only from outside. A top floor flat with a west facing wall of glass can be twelve degrees above the outside temperature by evening.')]),

dict(slug='air-conditioning-oldham', town='Oldham', county='Greater Manchester',
 postcodes='OL1 to OL9, including Saddleworth, Chadderton and Royton', drive='30 minutes',
 lat=53.5409, lon=-2.1114,
 title='Air Conditioning Oldham | Install &amp; Service | CoolIn',
 desc='Air conditioning and heat pumps in Oldham and Saddleworth. Stone terraces, Pennine weather and mill conversions. Free survey, 0% VAT on domestic work.',
 intro='Higher, colder and more exposed than most of Greater Manchester, which changes the sums. Around Saddleworth in particular, the heating side of an air conditioning system matters as much as the cooling, and stone walls behave differently to brick.',
 stock='Oldham sits between 150 and 300 metres above sea level in places. Winters run colder and longer than central Manchester, so we size and explain the heating performance carefully here.',
 local=[('Stone terraces and cottages','Thick gritstone walls hold temperature well once they reach it, which cuts both ways: slow to warm and slow to overheat. Core drilling takes considerably longer than through brick and we allow for that rather than discovering it on the day.'),
        ('Pennine winters','At 250 metres you see more days below 5°C than in the city, and that is where an air source heat pump works hardest for the least return. We are straight about it: the system will still heat, it will just take longer on the coldest mornings and you will want a second heat source.'),
        ('Mill conversions','Huge volumes, single glazed metal windows in some cases, and exposed brick with no insulation. Spot cooling in the occupied zones beats trying to condition the whole floor plate.'),
        ('Saddleworth villages','Conservation areas across Uppermill, Delph and Dobcross, plus a fair number of listed cottages. Outdoor unit position is a planning question before it is a technical one.')],
 faqs=[('Does a heat pump still work up on the Pennine edge in winter?',
        'Yes, but with less output as the temperature drops. Manufacturers rate units down to around minus 15°C and they keep producing heat there, just more slowly and less efficiently than at 7°C. Above about 200 metres you get more days below 5°C than central Manchester, so we size for that and tell you plainly to keep your existing heating for the coldest stretch rather than pretending it will replace it.'),
       ('Is drilling through stone a problem?',
        'Not a problem, just slower and more expensive in time than brick. A gritstone wall can be 500mm thick and takes a proper wet core drill and patience. It is worth knowing because a quote that assumes a standard 250mm brick wall will not survive contact with a Saddleworth cottage, and that is where mid job price rises come from.')]),

dict(slug='air-conditioning-rochdale', town='Rochdale', county='Greater Manchester',
 postcodes='OL11 to OL16, including Heywood, Milnrow and Littleborough', drive='35 minutes',
 lat=53.6097, lon=-2.1561,
 title='Air Conditioning Rochdale | Install &amp; Service | CoolIn',
 desc='Air conditioning in Rochdale, Heywood and Littleborough. Stone terraces, mill units and town centre retail. Free survey, 0% VAT on domestic installations.',
 intro='A mill town on the edge of the moors, with the housing stock and the weather to match. Solid stone terraces, large industrial units looking for practical cooling rather than comfort cooling, and a town centre that has been steadily rebuilt.',
 stock='Rochdale work leans commercial and industrial more than most of our patch, and the domestic side is dominated by solid wall terraces.',
 local=[('Solid wall terraces','Built before cavity walls, so heat moves through the fabric in both directions faster than a modern house. The heating and the cooling loads both run higher than the floor area alone would suggest and we size accordingly.'),
        ('Industrial and trade units','Dusty environments where standard filters block quickly. Heavier duty units, accessible filter positions and a service plan that reflects the conditions rather than a domestic schedule.'),
        ('Town centre retail','Shop floors trading with the door open, which is a cooling load most calculations ignore. Air curtains and correctly positioned units make far more difference than simply fitting something bigger.'),
        ('Littleborough and the moor edge','Exposed positions where wind driven rain hits the outdoor unit directly. Positioning and bracket choice matter more here than in a sheltered suburb.')],
 faqs=[('How often will filters need cleaning in a workshop?',
        'Far more often than in an office. A domestic or office system is fine on an annual clean with one interim check. In a workshop, joinery unit or anywhere with airborne dust, filters can block within a couple of months, and a blocked filter costs you both efficiency and, eventually, the compressor. We set the service frequency to the environment and show you how to pull and rinse the filters yourself between visits.'),
       ('Does leaving the shop door open make air conditioning pointless?',
        'Not pointless, but it changes the design. An open door is a continuous cooling load that most sizing calculations ignore entirely. The answer is usually a combination of a correctly sized system and an air curtain over the entrance, which costs less than upsizing the cooling and works considerably better.')]),

dict(slug='air-conditioning-bury', town='Bury', county='Greater Manchester',
 postcodes='BL8, BL9, and into Ramsbottom, Prestwich and Whitefield', drive='30 minutes',
 lat=53.5933, lon=-2.2966,
 title='Air Conditioning Bury | Install &amp; Service | CoolIn',
 desc='Air conditioning in Bury, Ramsbottom and Prestwich. Victorian semis, loft conversions and market town retail. Free survey, 0% VAT on domestic work.',
 intro='A market town with a wide mix: Victorian and Edwardian semis in Prestwich and Whitefield, stone properties as you climb towards Ramsbottom, and a busy retail and food scene around the market itself.',
 stock='Bury sits on the boundary between the brick built suburbs to the south and the stone built moorland towns to the north, and you can see it in the jobs.',
 local=[('Victorian and Edwardian semis','High ceilings, bay windows and, almost always, a loft conversion. The converted loft is the room that drives the enquiry, because it takes sun on the roof all day and sits above the warmest air in the house.'),
        ('Loft conversions','We size rooms in the roof about 20% above what the floor area alone suggests. It is the single most common reason a system fitted by someone else does not cope in August.'),
        ('Ramsbottom stone property','Thicker walls, longer core drilling and a colder position than the valley floor. Closer to an Oldham job than a Prestwich one.'),
        ('Market and town centre food','Small kitchens behind small frontages, where extract and make up air have to be designed together in a very tight space.')],
 faqs=[('Why does my loft conversion need more cooling than the room below?',
        'It gains heat from three directions instead of one. The roof above it is in direct sun for most of the day, the structure is lighter than a room lower down so it has less thermal mass to absorb that heat, and warm air from the rest of the house rises into it. We size loft rooms roughly 20% above a plain floor area calculation, which is the difference between holding temperature on a hot day and not.'),
       ('Can one outdoor unit serve the loft and two bedrooms?',
        'Yes, that is exactly what a multi split is for, and it keeps one condenser on the wall instead of three. The thing to watch is that the outdoor unit caps the total output shared between the indoor units, so we size it for the case where all three rooms are calling at once on a hot evening, not for the average.')]),

dict(slug='air-conditioning-macclesfield', town='Macclesfield', county='Cheshire East',
 postcodes='SK10 and SK11, including Bollington, Prestbury and Poynton', drive='45 minutes',
 lat=53.2587, lon=-2.1250,
 title='Air Conditioning Macclesfield | Install &amp; Service | CoolIn',
 desc='Air conditioning in Macclesfield, Prestbury and Bollington. Georgian and silk era property, listed buildings and Peak District edge. Free survey, 0% VAT.',
 intro='The old silk town, with Georgian and early Victorian property in the centre, substantial houses at Prestbury, and the ground rising sharply towards the Peak District on the eastern side. Listed buildings are common enough here to change the survey.',
 stock='Macclesfield has an unusual concentration of listed and locally significant buildings for a town its size, and the eastern side sits high enough to feel a genuinely different winter.',
 local=[('Listed and silk era buildings','No permitted development rights, so consent is needed before anything is fixed to the structure. We prepare the application with positions, noise data and photographs, and speak to the conservation officer before quoting rather than after.'),
        ('Prestbury and the larger houses','Whole house systems where the priority is keeping the number of visible outdoor units to a minimum and the pipework entirely out of sight.'),
        ('Rising ground to the east','Bollington and the lanes climbing towards the moors sit noticeably higher and colder than the town centre. Heating performance needs explaining honestly at those addresses.'),
        ('Town centre offices and clinics','Converted upper floors with awkward access and shared structures, where slim ducted units above a false ceiling usually beat a wall unit both visually and for the landlord.')],
 faqs=[('Can air conditioning go into a listed building in Macclesfield?',
        'Often, but it needs listed building consent because permitted development rights do not apply at all. What tends to get approved is a condenser in a rear courtyard or another position not visible from a public highway, with indoor units chosen to avoid drilling through historic fabric where there is any alternative. We put the application together and have the conversation with the conservation officer before you commit to anything.'),
       ('Is it worth having heating from it this side of the Peak District?',
        'Yes, for most of the year. Between roughly 7°C and 15°C outside, which covers a large part of a Cheshire autumn and spring, an air to air heat pump heats a room far more cheaply than firing a boiler to warm the whole house. On the genuinely cold weeks it gives less, and above 200 metres you get more of those weeks. We are clear about where the line falls for your specific address.')]),
]
