#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Writes _redirects: every .html address 301s to its clean form.

Netlify's pretty_urls post-processing was supposed to do this, and does not,
so the rules are stated explicitly instead. A splat cannot be used here because
Netlify only supports one at the end of a path, not /*.html, so every page gets
its own line. That is fine: the file is generated, never hand edited.

Runs after the pages are built, so it always matches what actually shipped.

    python3 tools/build-redirects.py
"""
import glob, os

os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))

pages = sorted(glob.glob('*.html') + glob.glob('blog/*.html') + glob.glob('case-studies/*.html'))
lines = ['# Generated by tools/build-redirects.py. Do not edit.',
         '# Every .html address sends a 301 to the clean one.', '']

for p in pages:
    if p == 'index.html':
        continue                      # netlify.toml already sends this to /
    if p == '404.html':
        continue                      # Netlify serves this for 404s, never link it
    clean = '/' + p[:-5]
    lines.append(f'/{p}{" " * max(1, 46 - len(p))}{clean}  301!')

lines.append('')
open('_redirects', 'w').write('\n'.join(lines))
print(f'  _redirects  {len([l for l in lines if l.startswith("/")])} rules')
